# This is a config for E2B sandbox template.
# You can use template ID (iwyd0wmbm7qp09tq0gtu) or template name (google-adk-template-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("google-adk-template-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("google-adk-template-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('google-adk-template-test')

team_id = "616aa5e1-9de6-4070-8d36-4050203b3604"
start_cmd = "./compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "google-adk-template-test"
template_id = "iwyd0wmbm7qp09tq0gtu"
